# Generated by Django 3.2.9 on 2021-11-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211117_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='user',
            name='school_address',
            field=models.CharField(max_length=20, null=True, verbose_name='학교주소'),
        ),
    ]
