# Generated by Django 3.2.9 on 2021-11-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardList',
            fields=[
                ('board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=25)),
                ('reporting_date', models.DateTimeField()),
                ('hit_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board_list',
                'managed': False,
            },
        ),
    ]
